# -*- coding: utf-8 -*-

# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1804, 924)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(330, 10, 1361, 621))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1359, 619))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label.setGeometry(QtCore.QRect(60, 40, 1271, 541))
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        #self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea.setWidget(self.label)
        self.axis3 = QtGui.QSlider(self.centralwidget)
        self.axis3.setGeometry(QtCore.QRect(380, 830, 1241, 22))
        self.axis3.setOrientation(QtCore.Qt.Horizontal)
        self.axis3.setObjectName(_fromUtf8("axis3"))
        self.axis2 = QtGui.QSlider(self.centralwidget)
        self.axis2.setGeometry(QtCore.QRect(380, 780, 1241, 22))
        self.axis2.setOrientation(QtCore.Qt.Horizontal)
        self.axis2.setObjectName(_fromUtf8("axis2"))
        self.axis1 = QtGui.QSlider(self.centralwidget)
        self.axis1.setGeometry(QtCore.QRect(380, 730, 1241, 22))
        self.axis1.setOrientation(QtCore.Qt.Horizontal)
        self.axis1.setObjectName(_fromUtf8("axis1"))
        self.addStructFile = QtGui.QPushButton(self.centralwidget)
        self.addStructFile.setGeometry(QtCore.QRect(260, 160, 51, 31))
        self.addStructFile.setObjectName(_fromUtf8("addStructFile"))
        self.currentAxis1 = QtGui.QLabel(self.centralwidget)
        self.currentAxis1.setGeometry(QtCore.QRect(1680, 730, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.currentAxis1.setFont(font)
        self.currentAxis1.setObjectName(_fromUtf8("currentAxis1"))
        self.currentAxis2 = QtGui.QLabel(self.centralwidget)
        self.currentAxis2.setGeometry(QtCore.QRect(1680, 780, 78, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.currentAxis2.setFont(font)
        self.currentAxis2.setObjectName(_fromUtf8("currentAxis2"))
        self.currentAxis3 = QtGui.QLabel(self.centralwidget)
        self.currentAxis3.setGeometry(QtCore.QRect(1680, 830, 78, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.currentAxis3.setFont(font)
        self.currentAxis3.setObjectName(_fromUtf8("currentAxis3"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 100, 231, 51))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 400, 181, 51))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 250, 271, 41))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.structEdit = QtGui.QLineEdit(self.centralwidget)
        self.structEdit.setGeometry(QtCore.QRect(10, 160, 251, 29))
        self.structEdit.setObjectName(_fromUtf8("structEdit"))
        self.viewOne = QtGui.QPushButton(self.centralwidget)
        self.viewOne.setGeometry(QtCore.QRect(360, 660, 361, 40))
        self.viewOne.setObjectName(_fromUtf8("viewOne"))
        self.viewTwo = QtGui.QPushButton(self.centralwidget)
        self.viewTwo.setGeometry(QtCore.QRect(780, 660, 381, 40))
        self.viewTwo.setObjectName(_fromUtf8("viewTwo"))
        self.viewThree = QtGui.QPushButton(self.centralwidget)
        self.viewThree.setGeometry(QtCore.QRect(1220, 660, 351, 40))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.viewThree.setFont(font)
        self.viewThree.setObjectName(_fromUtf8("viewThree"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1600, 660, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.layoutWidget = QtGui.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(270, 720, 91, 141))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout.addWidget(self.label_13)
        self.zoomIn = QtGui.QPushButton(self.centralwidget)
        self.zoomIn.setGeometry(QtCore.QRect(280, 10, 51, 40))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.zoomIn.setFont(font)
        self.zoomIn.setObjectName(_fromUtf8("zoomIn"))
        self.zoomOut = QtGui.QPushButton(self.centralwidget)
        self.zoomOut.setGeometry(QtCore.QRect(280, 50, 51, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.zoomOut.setFont(font)
        self.zoomOut.setObjectName(_fromUtf8("zoomOut"))
        self.cartCombo = QtGui.QComboBox(self.centralwidget)
        self.cartCombo.setGeometry(QtCore.QRect(10, 320, 251, 29))
        self.cartCombo.setObjectName(_fromUtf8("cartCombo"))
        self.t2Combo = QtGui.QComboBox(self.centralwidget)
        self.t2Combo.setGeometry(QtCore.QRect(10, 460, 251, 29))
        self.t2Combo.setObjectName(_fromUtf8("t2Combo"))
        self.addT2File = QtGui.QPushButton(self.centralwidget)
        self.addT2File.setGeometry(QtCore.QRect(260, 460, 51, 31))
        self.addT2File.setObjectName(_fromUtf8("addT2File"))
        self.addCartFile = QtGui.QPushButton(self.centralwidget)
        self.addCartFile.setGeometry(QtCore.QRect(260, 320, 51, 31))
        self.addCartFile.setObjectName(_fromUtf8("addCartFile"))
        self.loadButton = QtGui.QPushButton(self.centralwidget)
        self.loadButton.setGeometry(QtCore.QRect(0, 560, 331, 71))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.loadButton.setFont(font)
        self.loadButton.setObjectName(_fromUtf8("loadButton"))
        self.cartDistribution = QtGui.QPushButton(self.centralwidget)
        self.cartDistribution.setGeometry(QtCore.QRect(20, 720, 231, 141))
        self.cartDistribution.setObjectName(_fromUtf8("cartDistribution"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Cartilage Map Viewer", None))
        self.addStructFile.setText(_translate("MainWindow", "Add", None))
        self.currentAxis1.setText(_translate("MainWindow", "0", None))
        self.currentAxis2.setText(_translate("MainWindow", "0", None))
        self.currentAxis3.setText(_translate("MainWindow", "0", None))
        self.label_3.setText(_translate("MainWindow", "Structural Image File", None))
        self.label_5.setText(_translate("MainWindow", "T2 Image File", None))
        self.label_4.setText(_translate("MainWindow", "Cartilage Map Image File", None))
        self.viewOne.setText(_translate("MainWindow", "View 1", None))
        self.viewTwo.setText(_translate("MainWindow", "View 2", None))
        self.viewThree.setText(_translate("MainWindow", "View 3", None))
        self.label_6.setText(_translate("MainWindow", "Current Location", None))
        self.label_11.setText(_translate("MainWindow", "Axis 1", None))
        self.label_12.setText(_translate("MainWindow", "Axis 2", None))
        self.label_13.setText(_translate("MainWindow", "Axis 3", None))
        self.zoomIn.setText(_translate("MainWindow", "+", None))
        self.zoomOut.setText(_translate("MainWindow", "-", None))
        self.addT2File.setText(_translate("MainWindow", "Add", None))
        self.addCartFile.setText(_translate("MainWindow", "Add", None))
        self.loadButton.setText(_translate("MainWindow", "Load", None))
        self.cartDistribution.setText(_translate("MainWindow", "Cartilage Distribution", None))

